footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: link_chassis_1
update_frequency: 15
publish_frequency: 15.0
transform_tolerance: 0.1

resolution: 0.02

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /m2wr1/laser/scan, inf_is_valid: true}

inflation:
    inflation_radius: 1.0
